services:
  recommendation-service:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - recommendation-net

  redis:
    image: redis:7-alpine
    container_name: recommendation-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - recommendation-net

networks:
  recommendation-net:
